language: node_js
node_js:
    - node

before_install: cd sources/
script:
    - npm run build
    - npm run test
deploy:
    provider: npm
    skip_cleanup: true
    email: koliberr136a1@gmail.com
    api_key: $NPM_TOKEN
    on:
        branch: develop
